# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-11 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('tel_number', models.IntegerField()),
                ('card_number', models.IntegerField(max_length=20)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trasaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Оплата', 'Оплата'), ('Оплата бонусами', 'Оплата бонусами'), ('Начисление бонусов', 'Начисление бонусов')], max_length=3)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date', models.DateField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bonus_account.Account')),
            ],
        ),
    ]
