# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-11 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.IntegerField(),
        ),
    ]
