# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-11 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_account', '0002_auto_20210411_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasaction',
            name='type',
            field=models.CharField(choices=[('Оплата', 'Оплата'), ('Оплата бонусами', 'Оплата бонусами'), ('Начисление бонусов', 'Начисление бонусов')], max_length=10),
        ),
    ]
