# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-11 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_account', '0003_auto_20210411_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus_account.Account'),
        ),
        migrations.AlterField(
            model_name='trasaction',
            name='type',
            field=models.CharField(choices=[('Оплата', 'Оплата'), ('Оплата бонусами', 'Оплата бонусами'), ('Начисление бонусов', 'Начисление бонусов')], max_length=18),
        ),
    ]
