# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-11 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_account', '0004_auto_20210411_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasaction',
            name='number',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
