# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-11 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_account', '0005_trasaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
    ]
