# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-11 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_account', '0006_auto_20210411_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.IntegerField(verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='account',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tel_number',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='trasaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus_account.Account', verbose_name='Акаунт'),
        ),
        migrations.AlterField(
            model_name='trasaction',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='trasaction',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='trasaction',
            name='type',
            field=models.CharField(choices=[('Оплата', 'Оплата'), ('Оплата бонусами', 'Оплата бонусами'), ('Начисление бонусов', 'Начисление бонусов')], max_length=18, verbose_name='Тип'),
        ),
    ]
