# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-11 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_account', '0007_auto_20210411_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trasaction',
            name='number',
        ),
    ]
