# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-13 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_account', '0008_remove_trasaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.PositiveIntegerField(verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tel_number',
            field=models.PositiveIntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='trasaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus_account.Account', verbose_name='Аккаунт'),
        ),
    ]
