# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-14 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_account', '0009_auto_20210413_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Баланс'),
        ),
    ]
